language: node_js

node_js:
  - node

addons:
  ssh_known_hosts: $IP

before_install:
  - openssl aes-256-cbc -K $encrypted_08a6b5141aa3_key -iv $encrypted_08a6b5141aa3_iv
    -in travis.enc -out ~/.ssh/travis -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis
  - ssh-add ~/.ssh/travis
  - npm install -g yarn

install:
  - yarn install

script:
  - chmod +x ./deploy.sh
  - ./deploy.sh

notifications:
  email:
    on_failure: change

cache:
  directories:
    - $(npm config get prefix)/lib/node_modules/yarn
    - node_modules
    - ~/.ssh
